# Generated by Django 4.2.7 on 2023-11-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postBoard', '0004_post_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='type_tags',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(choices=[('nightlife', 'Nightlife'), ('sightseeing', 'Sightseeing'), ('gastronomy', 'Gastronomy'), ('culture', 'Culture'), ('shopping', 'Shopping'), ('relaxation', 'Relaxation'), ('history', 'History'), ('adventure', 'Adventure'), ('accomodation', 'Acoomodation'), ('nature', 'Nature'), ('festivals', 'Festivals'), ('beach', 'Beach')], default='sightseeing', max_length=50),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
