# Generated by Django 4.2.7 on 2023-11-29 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postBoard', '0005_remove_post_type_tags_post_tags_delete_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='public',
        ),
    ]
