# Generated by Django 4.2.7 on 2023-11-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postBoard', '0006_remove_post_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(choices=[('', 'Holiday Type'), ('nightlife', 'Nightlife'), ('sightseeing', 'Sightseeing'), ('gastronomy', 'Gastronomy'), ('culture', 'Culture'), ('shopping', 'Shopping'), ('relaxation', 'Relaxation'), ('history', 'History'), ('adventure', 'Adventure'), ('accomodation', 'Acoomodation'), ('nature', 'Nature'), ('festivals', 'Festivals'), ('beach', 'Beach')], default='sightseeing', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='world_area',
            field=models.CharField(choices=[('', 'Wolrd Area'), ('north_america', 'North America'), ('south_america', 'South America'), ('europe', 'Europe'), ('south_asia', 'South Asia'), ('east_asia', 'East Asia'), ('west_asia', 'West Asia'), ('oceania', 'Oceania'), ('africa', 'Africa'), ('middle_east', 'Middle East')], default='europe', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='most_visited_area',
            field=models.CharField(choices=[('', 'Wolrd Area'), ('north_america', 'North America'), ('south_america', 'South America'), ('europe', 'Europe'), ('south_asia', 'South Asia'), ('east_asia', 'East Asia'), ('west_asia', 'West Asia'), ('oceania', 'Oceania'), ('africa', 'Africa'), ('middle_east', 'Middle East')], max_length=50),
        ),
    ]
