# Generated by Django 4.2.7 on 2023-12-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postBoard', '0015_userprofile_profile_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='sign_on',
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(choices=[('', 'Holiday Type'), ('Nightlife', 'Nightlife'), ('Sightseeing', 'Sightseeing'), ('Gastronomy', 'Gastronomy'), ('Culture', 'Culture'), ('Shopping', 'Shopping'), ('Relaxation', 'Relaxation'), ('History', 'History'), ('Adventure', 'Adventure'), ('Stays', 'Stays'), ('Nature', 'Nature'), ('Festivals', 'Festivals'), ('Beach', 'Beach')], default='sightseeing', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='world_area',
            field=models.CharField(choices=[('', 'Wolrd Area'), ('North America', 'North America'), ('South America', 'South America'), ('Europe', 'Europe'), ('South Asia', 'South Asia'), ('East Asia', 'East Asia'), ('West Asia', 'West Asia'), ('Oceania', 'Oceania'), ('Africa', 'Africa'), ('Middle East', 'Middle East')], default='europe', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='most_visited_area',
            field=models.CharField(choices=[('', 'Wolrd Area'), ('North America', 'North America'), ('South America', 'South America'), ('Europe', 'Europe'), ('South Asia', 'South Asia'), ('East Asia', 'East Asia'), ('West Asia', 'West Asia'), ('Oceania', 'Oceania'), ('Africa', 'Africa'), ('Middle East', 'Middle East')], max_length=50),
        ),
    ]
